### ISSUE TITLE
UCSC: Univ. California Santa Cruz

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#136]
MVZ met with folks from UCSC over the summer, and Alex Krohn (former grad student) is the primary contact. He filled out the old Jotform questionnaire but I have asked him to fill out the new collection form in Arctos. MVZ folks (Michelle, Carol, Carla) can be the mentors. See email to AWG 8/28/2018 with Michelle's responses.

[Arctos_Participation_Initial_Questionnaire_August28.pdf](https://github.com/ArctosDB/new-collections/files/2329189/Arctos_Participation_Initial_Questionnaire_August28.pdf)

**Comment by Jegelewicz** [comment]
**Questionnaire completed by**
Alex Krohn

**Job Title**
Assistant Director

**Email**
arkrohn@ucsc.edu

**Phone**
9086424726

**Status**
new

**Link**
https://arctos.database.museum/new_collection.cfm?action=manage&id=E3F00FCB81BE4D92D9B14900F9CF9913

**Institution Acronym**
UCSC

**Institution**
Kenneth S. Norris Center for Natural History, University of California, Santa Cruz (UCSC)

**How many total specimens across all collection(s) are you interested in migrating to Arctos?**
8300

**Are the data for all of those specimens in digital format?**
no

**Which of the following specimen types are you interested in migrating to Arctos (check all that apply)?**
Amphibians,Reptiles,Fishes,Birds,Mammals

**On average, how many specimens have been added to the collection(s) annually over the past 5 years?**
100

**How do you expect this rate of growth to change in the foreseeable future?**
Increase

What software do you currently use to manage specimen data (e.g., e.g., Access, Filemaker Pro, Excel, Specify-indicate which version, etc.)?
Excel or Google Drive, if any.

**How are your data structured in your current information system (flat table, related tables, disjoined tables, etc.)?**
Flat tables

**Do you use controlled vocabularies or authority files for the following kinds of data (check all that apply)?**
none

**Do you allow free text data entry for the following kinds of data (check all that apply)?**
Agents,Taxonomy,Geography,Specimen Parts

**Is it possible to bypass the controlled vocabularies or authority files? Explain**
Yes. None exists.

**Please expand on how you deal with agents, taxonomy, geography, and/or specimen parts.**
The majority of our data is stored in handwritten ledgers, without any controlled vocabulary.

**How do you deal with tissues in your collection?**
Tissues are entered as free-form text in a remarks or comment field.,There are no tissues in our collection.

**Describe any other details about how you deal with tissues currently, or plan to deal with them in the future.**
There are currently only ~50 tissues for the 8000 specimens that we wish to include. For future specimens we would like to take tissue samples, but we do not currently have the ability to store large volumes of tissues in perpetuity.

**Do you use machine-readable labels (such as barcodes) to digitally track any objects in your collections?**
no

**Describe any details about you incorporate barcodes into your current system, or whether you plan to deal with them in the future.**
No plans yet. If our operations grew, we might, but right now we have no need or plans.

**Describe how you deal with locality information (including coordinates, if any) in your current collection management system.**
Some specimens have coordinates (usually lat/long without datum or error), if they were included. A lot are vague localities (e.g. "Santa Cruz").

**Approximately what proportion of your locality data are georeferenced with latitude/longitude coordinates?**
5%

**Describe the kinds of metadata that you store with your coordinate information (e.g., datum, GPS error, extent, maximum uncertainty, georeferencing method, etc.)**
None

**For the following transaction types, indicate whether you have digital information that would need to be formatted and imported? (check all that apply)**
none

**Describe generally how you deal with transactions (loans, accessions, permits) in your current system.**
We use a Google Sheet and have previously used paper checkout sheets.

**Other than basic “label data” (who/what/when/where), what other kinds of information (if any) is recorded about your specimens (e.g., citations in publications, GenBank numbers, projects, etc.)?**
None

**Do you have digital media in your current system?**
yes

**Indicate how you plan to store digital media that are linked to data in Arctos.**
We need storage for digital media through Arctos.,Our digital media are stored and accessible via an external web service.

**Do you have someone familiar with the collection who can assist in migrating data to Arctos?**
yes

**Please describe any permission or security issues that would prevent us from accessing your data directly if necessary for data migration?**
NA

**Do you have an annual budget available for database support?**
no

**Please add any other comments or questions that you have re: Arctos or your collection(s).**
Lots of them! Some have already been conveyed to Arctos staff. One example follows. We currently have other much larger collections (insects and plants, 82,000 specimens total) stored in other database systems (SCAN and NANSH, respectively). Those systems work to make our specimens accessible, but are not helpful for processing loans, tracking use etc., as Arctos would. We would like to have one database to rule them all!! Is it possible to integrate these data into Arctos without creating 82,000 duplicate records? We are also interested in digitizing and/or transcribing numerous field notes to associate with specimens. Could we process these in Arctos just like we would an image of a specimen?

**Comment by Jegelewicz** [comment]
It's official! The Norris Center is ready to use Arctos for our specimen management system. We're extremely excited to have our specimens publicly available, part of GBIF and other aggregators, and excited about the transactions management system/specimen use tracking features in Arctos.

    I filled out the initial questionnaire, but figured one of you could point me in the right direction to get set up with an MOU. From there, I can start adding the collections and staff to GRBio (we've already got an institutional acronym through our herbarium, UCSC, so these would just be additional collections at the same institution).

Carla is the one with the most experience with MOU's (especially our new workflow for new collections) so I am going to let her take this one. 


    I had three questions about Arctos that are somewhat specific to our institution. First, I'm interested in initially adding the vertebrate collections to Arctos (~8,300 specimens). Eventually I'd like to add the plant and insect collections as well (~84,000 specimens). The plant and insect collections are already digitized on NANSH and SCAN, respectively, but those platforms lack the relational nature and the transaction management system of Arctos. Ideally, Arctos would be the one system to rule them all! Is there a way to easily add those specimens to Arctos without duplicating the records? 

 NANSH and SCAN are Symbiota so in theory, yes, they can be bulkloaded. Let me ask Joyce and John (berkeley natural history museum programmers) who have a little more experience with Symbiota (and Joyce will be dealing wtih their programmers directly soon) to find out the best way to deal with that. I assume that is what you meant by "without duplicating the records". Once there, Arctos should be the spot for new entries and a new pipeline from Arctos to Symbiota should be established to keep the Symbiota portal updated. 


    Second, we will soon be adding many new specimens to our collections (thus our interest in digitization and better organization!). I would love to take tissue samples for these specimens, but we currently don't have the capacity to properly store, subsample, loan, etc. thousands of tissue samples for the long term. Given our mostly teaching/outreach focus, I doubt this would be a high priority for our limited budget. Does the MVZ, or other institutions, ever take tissue samples from other museums if the specimens associated with the samples are publicly searchable and accessible through Arctos? I'm happy to take additional steps (creating an MOU, finding funds for tubes/LN2 doers etc.) here to make this happen, if it's at all possible.

That does happen. For example, we have tissues for many herp specimens that are cataloged at the California Academy of Sciences which is dependent on the collectors arrangement.  The tissues would really be a donation to the MVZ and we would accession them as our specimens with reference to your catalog numbers. Since it would be in Arctos, those cross-collection, cross-institutional relations would be easy to make and see. But to make this a longterm arrangement, funds to help support this would be essential. (technically not a problem)


    Finally, we've got lots of field notes that we've started digitizing and/or transcribing. I'd love to associate these field notes with the specimens they describe. Does the MVZ add field notes directly to Arctos as images, or are the MVZ Archives separate from Arctos? For a museum starting fresh, what would you recommend?

oh boy, let's talk more about this one! There's a number of things afoot in archives but a quick response is that all our archival materials (field notes,etc) are cataloged separately in a dedicated archival database (we are using Archivist Toolkit right now and hope to migrate to the newer ArchivesSpace). Digital versions are available via URL on Internet Archive and Texas Advanced Computing Center. Arctos can still tag and link to these externally as media, which we do as well. Let me think about the best way starting fresh and I will consult with our archivist here too.


    Thanks for your help, and looking forward to working with you all on this migration!!

Me, too. Talk to you soon! MK
