### ISSUE TITLE
Arkansas CBC Collection Portal Request

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#91]
Institution contact requests collection portal creation. Please use the form at Reports/CollectionCreationRequest or http://arctos.database.museum/new_collection.cfm

**Comment by Jegelewicz** [comment]
Initial form complete. Need to settle on institution acronym before proceeding. See #90

**Comment by campmlc** [comment]
[Arkansas State University portal mock up.docx](https://github.com/ArctosDB/new-collections/files/2288892/Arkansas.State.University.portal.mock.up.docx)

Call with Travis Marsico and Diana Soteropoulos (Herbarium data manager) to submit new online collections request form and discuss setup of new portal. Issue is whether to keep existing herbarium records under "STAR" portal and vertebrate records under "ASUMZ" portal. Both are now subsumed under Arkansas Center for Biodiversity Collections (ACBDC). The Star acronym is on barcodes affixed to herbarium records, and this is what they want cited. But the format is "STAR_000001". Possible suggestion to use ACBC as institution, Herb, Mamm, Fish etc as collections, and add STAR and ASUMZ numbers as other IDs. See their mockup for most recent.

Thank you for talking us through our first steps as members of the Arctos community. Please find a mock up of how we want the Arkansas State University portal to appear on Arctos. It is based on the University of Alaska Museum portal.

We would like the entire collection to have the acronym ACBC, to reflect the unification of all the natural history collections at Arkansas State University through the Arkansas Center for Biodiversity Collections. For the first box under our portal name, we want to explain what the ACBC is, then have explanatory boxes for our plant collections (under STAR) and animal collections (under ASUMZ).

Next, each collection will appear with a description of the holdings, e.g., Plant specimens (STAR) (ACBC:Herb), etc.

We have requested each curator provide a written description of their collections to include on the portal. Please let us know if this format will work and if there is any additional information you need from us at this time.

I will be sending a spreadsheet of herbarium databased records later this evening.
Diana

**Comment by campmlc** [comment]
I just asked for clarification on the two "ACBC:Herb" collections.
@lkvoong 
@Jegelewicz

**Comment by dustymc** [comment]
They have have a million collections that use the Herb code tables, but GUID_Prefix must be unique. I think current Herb attributes probably apply fairly well to "things more or less curated by folks who hang around with botanists" - it's pretty generic. http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE&coln=Herb

**Comment by campmlc** [comment]
How about "ACBC:Alg"? Diatoms are algae, after all.

**Comment by campmlc** [comment]
They are OK with ACBC:Alg

**Comment by campmlc** [comment]
Finalized decision on Arkansas State collection portal and guids:
Redirecting from #90
[Arkansas State University portal mock up-v2.docx](https://github.com/ArctosDB/new-collections/files/2372372/Arkansas.State.University.portal.mock.up-v2.docx)

@lkvoong  please delete the ACBC:Herb collection portal.

The multi-collection portal for the institution should be "Arkansas Biodiversity Collections (ABDC)"
The herbarium will be under the institutional acronym STAR, with the following guids:
STAR:Herb
STAR:Alg
The zoological collections will be under the institutional acronym ASUMZ, with the following guids:
ASUMZ:Herp
ASUMZ:Mamm
ASUMZ:Ento
ASUMZ:Bird
ASUMZ:Fish
ASUMZ:Invert
ASUMZ:Bivalve or ASUMZ: Mala - for their bivalve collection. Any reason to insist on one vs the other?
@dustymc

**Comment by dustymc** [comment]
>delete the ACBC:Herb

I don't believe it was ever created. In general (and pending better ideas) we're not going to create collections until the details regarding collections (particularly GUID) have been ironed out and the flag is set to "approved to create collections" in the new collections form.

I'm not sure we want to formalize anything, but I would like a better review process. GUIDs should be stable - changing them should involve something like the collection being moved to a new Institution (and even then I'd try to keep the GUIDs). I don't think the current process is nearly rigorous enough. Can we add some final communication/review involving everyone we can think of or similar? At least Lam, I, the collection representative, and the mentor should somehow be absolutely sure we're all on the same page before we create something that should never be un-created.

GUID_Prefix is mostly an arbitrary string - ASUMZ:Bivalve and ASUMZ:Mala (and most anything else) are functionally identical.

**Comment by campmlc** [comment]
It was created as pre- pre- collection, and I would like it removed before
approving to create collections. Delete button?
Happy to have formal review for collections creation. Asking for feedback
has gotten little response.

**Comment by dustymc** [comment]
Ah - you can just change it in that form. Change it to DELETE or something equally obvious if you've already created a replacement.

**Comment by campmlc** [comment]
Help please - There are three new collections requests for Arkansas State, and one needs to be deleted. I cannot do this from the interface.  ACBC:Herb needs to be deleted- because they have decided to keep their previous herbarium institution code of STAR, and use the ACBC acronym as the multicollections portal.   If I change collection status to 'denied" I get an error. Also there are two separate collections portals request for STAR:Herb and STAR:Alg. All of these have identical information for new collections, including the defunct ACBC request. I can't find any way to delete or approve. I'm attaching the file of what we need to create for the multicollections portal.

[ACBC Arctos descriptions_updated 20180917.docx](https://github.com/ArctosDB/new-collections/files/2417258/ACBC.Arctos.descriptions_updated.20180917.docx)

**Comment by dustymc** [comment]
I fixed the error. Approval is by institution, so I'm sort of glad it was there...

Is Arkansas State University Zoological Collections (ASUMZ) a different institution (eg, do we send them a separate bill?)?

I changed the GUID_PREFIX to "delete" for the one I think you don't want.

soteropoulosd2 needs to be an active operator before we create.

I'm not sure what "use the ACBC acronym as the multicollections portal." means. I don't think portals can have colons in them - we can use ACBC_ALL or ACBC_WHATEVER or STAR_WHATEVER or a few of those, but that has nothing to do with GUID_Prefix - portals are just users with READ access to certain collections.

Required things are yellow - I'm not sure what you mean by that.

Per https://github.com/ArctosDB/new-collections/issues/91#issuecomment-420400687, I'd like to get more eyes on this, particularly the GUIDs - is everyone SURE those are going to work forever? - before we create. The link is http://arctos.database.museum/new_collection.cfm?action=manage&id=909AB1A32F72FE3D9C362AEAA8538D00 - scroll down to see the two collections.

**Comment by campmlc** [comment]
Is Arkansas State University Zoological Collections (ASUMZ) a different institution (eg, do we send them a separate bill?)? 
No, the MOU is with the Arkansas Center for Biodiversity Collections of ASU . Both ASUMZ (Zoology) and STAR (Herbarium) have been recently combined under the same institution (Arkansas Center for Biodiversity Collections.) But they want to retain their original institutional names and collection codes. 

ACBC Multicollection portal should be modeled after UAM. Lam has said this is possible. The colon isn't necessary and can be modified to whatever is consistent with similar collections.

Required things are yellow: e.g. white boxes in the form turned out to be required for submission. In all other Arctos forms, required fields are all yellow.
![image](https://user-images.githubusercontent.com/14808196/46052710-c8536400-c0fc-11e8-9640-fe270a241feb.png)

Per #91 (comment), I'd like to get more eyes on this, particularly the GUIDs - is everyone SURE those are going to work forever? - before we create. The link is http://arctos.database.museum/new_collection.cfm?action=manage&id=909AB1A32F72FE3D9C362AEAA8538D00 - scroll down to see the two collections.

I've been asking for advice and feedback on the GUIDs and multicollections portal concept for 6 weeks. The guids have been discussed and vetted with all the collection personnel at ASU. The only question I have remaining is whether we should use "Mala" for their bivalve collection, or "Bivalve" as they originally suggested. They have another aquatic macroinvertebrates collection that includes some molluscs; their bivalve collection is specifically that.

**Comment by dustymc** [comment]
> multicollections portal concept...weeks

Sorry, we just figured you'd sort that out or they were trying to settle on GUIDs or something. Portals docs are http://handbook.arctosdb.org/how_to/understanding-portals.html - I'll add something about the format. Any combination of collections can be a portal. As long as that's the need and they have some flexibility on the names (eg, underbars vs. colons), it should all be good.

I think getting them all under the same request is going to be less confusing in creating collections, finding mentors and such, and maybe billing (@Jegelewicz  ?). GUIDs are arbitrary strings here too - I don't care what they call themselves, I just want to know who to talk to when I have a problem. I can shuffle things around in the form if that's useful.

> The guids have been discussed and vetted with all the collection personnel at ASU. 

Close enough for me.

>"Mala" for their bivalve collection, or "Bivalve" as they originally suggested. 

Whichever one they're less likely to want to change, followed closely by whichever one is less likely to confuse users, all with the understanding that it's just a very permanent string and there's no reason to panic when someone finds a snail hiding in the corner. Makes absolutely no difference to me, and a few minutes of poking around GBIF suggests there's no overwhelming trend. (Finally, a place GRBIO might be useful - and they're not there...)

**Comment by campmlc** [comment]
Please combine the two forms/requests under one institution "Arkansas
Center for Biodiversity Collections",  The ACBC includes all natural
history collections at Arkansas State University, including the herbarium
(STAR) and animal (ASUMZ) collections - following their mockup pattern.

I'll confirm when I talk to them on Thursday about the Bivalve collections.

Apparently GBIF is taking over GRBIO - hence the downtime?

**Comment by dustymc** [comment]
Done. I left http://arctos.database.museum/new_collection.cfm?action=manage&id=909AB1A32F72FE3D9C362AEAA8538D00 just in case it has something useful hiding out somewhere. Everything should be available under http://arctos.database.museum/new_collection.cfm?action=manage&id=41DF8B3B3A40DB7E33BB42DEEDF6B4C3

> GBIF is taking over GRBIO -

IF they get rid of the silly idea that institution_code + collection_code is unique - and that should be obvious from GBIF's data - that could be a useful thing. Here's hoping....

**Comment by Jegelewicz** [comment]
> I think getting them all under the same request is going to be less confusing in creating collections, finding mentors and such, and maybe billing.

Yes, I would like to have a portal for each billable institution that includes all collections that will be billed together. Alaska desperately needs this....

**Comment by campmlc** [comment]
Collections are approved for creation under portal of Arkansas State Biodiversity Collections.  All collection contacts are users in Arctos, but only Diana Soteropoulos is an ACBC operator at this point. She and I should be operators for all collections. If other users must be operators prior to portal creation, delete them from the portals until we get the collections up and running and I will take care of geting them set up.
 I would recommend against forcing users to be operators prior to portal creation requirement because it adds extra steps of having to create them as as operators with no collection to tie them to, and then later go in and assign them to collections and collection roles. It would be easier to do this all at once after the portals exist.
@lkvoong

**Comment by campmlc** [comment]
All operator names have been updated. Please create collections. We would like to have this completed by 10/5/18.
@lkvoong

**Comment by Jegelewicz** [comment]
Portals exist in Arctos - closing
